make probes smarter (hopefully)

diff --git a/apps/usenet/sabnzbd/configmap.yaml b/apps/usenet/sabnzbd/configmap.yaml
--- a/apps/usenet/sabnzbd/configmap.yaml
+++ b/apps/usenet/sabnzbd/configmap.yaml
@@ -37,3 +37,24 @@ data:
     echo "finished merging subtitles"
 
     exit 0
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: sabnzbd-startup
+  namespace: usenet
+data:
+  startup_probe.sh: |
+    #!/usr/bin/env bash
+    if ! command -v mkvmerge >/dev/null; then
+      echo "mkvmerge not found"
+      exit 1
+    fi
+    if [ ! -f /app/sabnzbd/scripts/merge_subtitles.sh ]; then
+      echo "merge_subtitles.sh not found"
+      exit 1
+    fi
+    if [ $(curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8080) != "200" ]; then
+      echo "sabnzbd not ready"
+      exit 1
+    fi
